#! /bin/bash

if [ "$#" -lt 2 ]; then
    echo "Erro: forneça o nome do arquivo de saida e ao menos um arquivo para compactar."
    exit 1
fi

arquivo_saida="$1"
arquivos=("${@:2}")

tar -czf "$arquivo_saida" "${arquivos[@]}"

echo "Compactação concluida: $arquivo_saida"
